// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BlrtRcpp
Rcpp::NumericVector BlrtRcpp(Rcpp::NumericVector prior_null, Rcpp::NumericVector prob_null, Rcpp::NumericVector prior_alt, Rcpp::NumericVector prob_alt, std::size_t n_data, Rcpp::IntegerVector n_outcomes_int, std::size_t n_bootstrap, std::size_t n_rep, std::size_t n_thread, unsigned int max_iter, double tolerance, Rcpp::IntegerVector seed);
RcppExport SEXP _poLCAParallel_BlrtRcpp(SEXP prior_nullSEXP, SEXP prob_nullSEXP, SEXP prior_altSEXP, SEXP prob_altSEXP, SEXP n_dataSEXP, SEXP n_outcomes_intSEXP, SEXP n_bootstrapSEXP, SEXP n_repSEXP, SEXP n_threadSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior_null(prior_nullSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prob_null(prob_nullSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior_alt(prior_altSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prob_alt(prob_altSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_data(n_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_outcomes_int(n_outcomes_intSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_bootstrap(n_bootstrapSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_rep(n_repSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_thread(n_threadSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(BlrtRcpp(prior_null, prob_null, prior_alt, prob_alt, n_data, n_outcomes_int, n_bootstrap, n_rep, n_thread, max_iter, tolerance, seed));
    return rcpp_result_gen;
END_RCPP
}
// EmAlgorithmRcpp
Rcpp::List EmAlgorithmRcpp(Rcpp::NumericMatrix features, Rcpp::IntegerMatrix responses, Rcpp::NumericVector initial_prob, std::size_t n_data, std::size_t n_feature, Rcpp::IntegerVector n_outcomes_int, std::size_t n_cluster, std::size_t n_rep, bool na_rm, std::size_t n_thread, unsigned int max_iter, double tolerance, Rcpp::IntegerVector seed);
RcppExport SEXP _poLCAParallel_EmAlgorithmRcpp(SEXP featuresSEXP, SEXP responsesSEXP, SEXP initial_probSEXP, SEXP n_dataSEXP, SEXP n_featureSEXP, SEXP n_outcomes_intSEXP, SEXP n_clusterSEXP, SEXP n_repSEXP, SEXP na_rmSEXP, SEXP n_threadSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type responses(responsesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_data(n_dataSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_feature(n_featureSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_outcomes_int(n_outcomes_intSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_cluster(n_clusterSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_rep(n_repSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_thread(n_threadSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(EmAlgorithmRcpp(features, responses, initial_prob, n_data, n_feature, n_outcomes_int, n_cluster, n_rep, na_rm, n_thread, max_iter, tolerance, seed));
    return rcpp_result_gen;
END_RCPP
}
// ylik
Rcpp::NumericVector ylik(Rcpp::NumericVector probs, Rcpp::IntegerVector y, int obs, int items, Rcpp::IntegerVector numChoices, int classes);
RcppExport SEXP _poLCAParallel_ylik(SEXP probsSEXP, SEXP ySEXP, SEXP obsSEXP, SEXP itemsSEXP, SEXP numChoicesSEXP, SEXP classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< int >::type items(itemsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type numChoices(numChoicesSEXP);
    Rcpp::traits::input_parameter< int >::type classes(classesSEXP);
    rcpp_result_gen = Rcpp::wrap(ylik(probs, y, obs, items, numChoices, classes));
    return rcpp_result_gen;
END_RCPP
}
// postclass
void postclass(Rcpp::NumericVector prior, Rcpp::NumericVector probs, Rcpp::IntegerVector y, int items, int obs, Rcpp::IntegerVector numChoices, int classes, Rcpp::NumericVector posterior);
RcppExport SEXP _poLCAParallel_postclass(SEXP priorSEXP, SEXP probsSEXP, SEXP ySEXP, SEXP itemsSEXP, SEXP obsSEXP, SEXP numChoicesSEXP, SEXP classesSEXP, SEXP posteriorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type items(itemsSEXP);
    Rcpp::traits::input_parameter< int >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type numChoices(numChoicesSEXP);
    Rcpp::traits::input_parameter< int >::type classes(classesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type posterior(posteriorSEXP);
    postclass(prior, probs, y, items, obs, numChoices, classes, posterior);
    return R_NilValue;
END_RCPP
}
// GoodnessFitRcpp
Rcpp::List GoodnessFitRcpp(Rcpp::IntegerMatrix responses, Rcpp::NumericVector prior, Rcpp::NumericVector outcome_prob, std::size_t n_data, Rcpp::IntegerVector n_outcomes_int, std ::size_t n_cluster);
RcppExport SEXP _poLCAParallel_GoodnessFitRcpp(SEXP responsesSEXP, SEXP priorSEXP, SEXP outcome_probSEXP, SEXP n_dataSEXP, SEXP n_outcomes_intSEXP, SEXP n_clusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type responses(responsesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome_prob(outcome_probSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_data(n_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_outcomes_int(n_outcomes_intSEXP);
    Rcpp::traits::input_parameter< std ::size_t >::type n_cluster(n_clusterSEXP);
    rcpp_result_gen = Rcpp::wrap(GoodnessFitRcpp(responses, prior, outcome_prob, n_data, n_outcomes_int, n_cluster));
    return rcpp_result_gen;
END_RCPP
}
// PosteriorRcpp
Rcpp::NumericMatrix PosteriorRcpp(Rcpp::IntegerVector responses, Rcpp::NumericVector probs, Rcpp::IntegerVector n_outcomes_int, Rcpp::NumericVector prior, std::size_t n_data, std::size_t n_cluster);
RcppExport SEXP _poLCAParallel_PosteriorRcpp(SEXP responsesSEXP, SEXP probsSEXP, SEXP n_outcomes_intSEXP, SEXP priorSEXP, SEXP n_dataSEXP, SEXP n_clusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type responses(responsesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_outcomes_int(n_outcomes_intSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_data(n_dataSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_cluster(n_clusterSEXP);
    rcpp_result_gen = Rcpp::wrap(PosteriorRcpp(responses, probs, n_outcomes_int, prior, n_data, n_cluster));
    return rcpp_result_gen;
END_RCPP
}
// LikelihoodRcpp
Rcpp::NumericMatrix LikelihoodRcpp(Rcpp::IntegerVector responses, Rcpp::NumericVector probs, Rcpp::IntegerVector n_outcomes_int, std::size_t n_data, std::size_t n_cluster);
RcppExport SEXP _poLCAParallel_LikelihoodRcpp(SEXP responsesSEXP, SEXP probsSEXP, SEXP n_outcomes_intSEXP, SEXP n_dataSEXP, SEXP n_clusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type responses(responsesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_outcomes_int(n_outcomes_intSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_data(n_dataSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_cluster(n_clusterSEXP);
    rcpp_result_gen = Rcpp::wrap(LikelihoodRcpp(responses, probs, n_outcomes_int, n_data, n_cluster));
    return rcpp_result_gen;
END_RCPP
}
// StandardErrorRcpp
Rcpp::List StandardErrorRcpp(Rcpp::NumericVector features, Rcpp::IntegerMatrix responses, Rcpp::NumericVector probs, Rcpp::NumericMatrix prior, Rcpp::NumericMatrix posterior, std::size_t n_data, std::size_t n_feature, Rcpp::IntegerVector n_outcomes_int, std::size_t n_cluster, bool use_smooth);
RcppExport SEXP _poLCAParallel_StandardErrorRcpp(SEXP featuresSEXP, SEXP responsesSEXP, SEXP probsSEXP, SEXP priorSEXP, SEXP posteriorSEXP, SEXP n_dataSEXP, SEXP n_featureSEXP, SEXP n_outcomes_intSEXP, SEXP n_clusterSEXP, SEXP use_smoothSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type responses(responsesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type posterior(posteriorSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_data(n_dataSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_feature(n_featureSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_outcomes_int(n_outcomes_intSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_cluster(n_clusterSEXP);
    Rcpp::traits::input_parameter< bool >::type use_smooth(use_smoothSEXP);
    rcpp_result_gen = Rcpp::wrap(StandardErrorRcpp(features, responses, probs, prior, posterior, n_data, n_feature, n_outcomes_int, n_cluster, use_smooth));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void d2lldbeta2(void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void probhat(void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_poLCAParallel_BlrtRcpp", (DL_FUNC) &_poLCAParallel_BlrtRcpp, 12},
    {"_poLCAParallel_EmAlgorithmRcpp", (DL_FUNC) &_poLCAParallel_EmAlgorithmRcpp, 13},
    {"_poLCAParallel_ylik", (DL_FUNC) &_poLCAParallel_ylik, 6},
    {"_poLCAParallel_postclass", (DL_FUNC) &_poLCAParallel_postclass, 8},
    {"_poLCAParallel_GoodnessFitRcpp", (DL_FUNC) &_poLCAParallel_GoodnessFitRcpp, 6},
    {"_poLCAParallel_PosteriorRcpp", (DL_FUNC) &_poLCAParallel_PosteriorRcpp, 6},
    {"_poLCAParallel_LikelihoodRcpp", (DL_FUNC) &_poLCAParallel_LikelihoodRcpp, 5},
    {"_poLCAParallel_StandardErrorRcpp", (DL_FUNC) &_poLCAParallel_StandardErrorRcpp, 10},
    {"d2lldbeta2", (DL_FUNC) &d2lldbeta2, 8},
    {"probhat",    (DL_FUNC) &probhat,    7},
    {NULL, NULL, 0}
};

RcppExport void R_init_poLCAParallel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
