# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BlrtRcpp <- function(prior_null, prob_null, prior_alt, prob_alt, n_data, n_outcomes_int, n_bootstrap, n_rep, n_thread, max_iter, tolerance, seed) {
    .Call(`_poLCAParallel_BlrtRcpp`, prior_null, prob_null, prior_alt, prob_alt, n_data, n_outcomes_int, n_bootstrap, n_rep, n_thread, max_iter, tolerance, seed)
}

EmAlgorithmRcpp <- function(features, responses, initial_prob, n_data, n_feature, n_outcomes_int, n_cluster, n_rep, na_rm, n_thread, max_iter, tolerance, seed) {
    .Call(`_poLCAParallel_EmAlgorithmRcpp`, features, responses, initial_prob, n_data, n_feature, n_outcomes_int, n_cluster, n_rep, na_rm, n_thread, max_iter, tolerance, seed)
}

ylik <- function(probs, y, obs, items, numChoices, classes) {
    .Call(`_poLCAParallel_ylik`, probs, y, obs, items, numChoices, classes)
}

postclass <- function(prior, probs, y, items, obs, numChoices, classes, posterior) {
    invisible(.Call(`_poLCAParallel_postclass`, prior, probs, y, items, obs, numChoices, classes, posterior))
}

GoodnessFitRcpp <- function(responses, prior, outcome_prob, n_data, n_outcomes_int, n_cluster) {
    .Call(`_poLCAParallel_GoodnessFitRcpp`, responses, prior, outcome_prob, n_data, n_outcomes_int, n_cluster)
}

PosteriorRcpp <- function(responses, probs, n_outcomes_int, prior, n_data, n_cluster) {
    .Call(`_poLCAParallel_PosteriorRcpp`, responses, probs, n_outcomes_int, prior, n_data, n_cluster)
}

LikelihoodRcpp <- function(responses, probs, n_outcomes_int, n_data, n_cluster) {
    .Call(`_poLCAParallel_LikelihoodRcpp`, responses, probs, n_outcomes_int, n_data, n_cluster)
}

StandardErrorRcpp <- function(features, responses, probs, prior, posterior, n_data, n_feature, n_outcomes_int, n_cluster, use_smooth) {
    .Call(`_poLCAParallel_StandardErrorRcpp`, features, responses, probs, prior, posterior, n_data, n_feature, n_outcomes_int, n_cluster, use_smooth)
}

